name: ecp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - graphviz
  - pandas==2.1.4
  - seaborn==0.13.2
  - numpy
  - scikit-learn
  - pip:
    - pydantic>=2.0.0,<3.0.0
    - dagster==1.11.2
    - dagster-dbt==0.27.2
    - dagster-webserver==1.11.2
    - dagster-gcp
    - dagster-gcp-pandas
    - dagster-duckdb-pandas
    - great_expectations==0.18.11
    - google-cloud-bigquery==3.0.0
    - google-cloud-bigquery-storage
    - google-auth
    - kaggle
    - dbt-core==1.8.0
    - dbt-bigquery==1.8.0
    - matplotlib==3.10.1
    - googletrans==4.0.0-rc1
    - upath
    - gcsfs
    - dagster-pandas
    - minisom
    - kneed