name: ecp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - graphviz
  - pandas==2.1.4
  - seaborn==0.13.2

  - pip:
    # Explicitly pin pydantic to a known Python 3.10 compatible v2 version
    - pydantic==2.7.1

    # Align dagster and dagster-webserver to match dagster-dbt's dependency
    - dagster==1.10.20
    - dagster-dbt==0.26.20
    - dagster-webserver==1.10.20
    - dagster-gcp
    
    # Other packages
    - great_expectations==1.5.1
    - google-cloud-bigquery
    - google-cloud-bigquery-storage
    - google-auth
    - kaggle
    - dbt-core==1.9.8
    - dbt-bigquery==1.9.2
    - matplotlib==3.10.1
    - googletrans==4.0.0-rc1