name: olist_ecommerce
version: 1.0.0
config-version: 2
profile: olist_ecommerce
model-paths:
- models
seed-paths:
- seeds
macro-paths:
- macros
- dbt_packages/dbt_expectations/macros  
target-path: target
clean-targets:
- target
- dbt_packages
snapshot-paths:
- snapshots

models:
  olist_ecommerce:
    staging:
      +materialized: view  
      +schema: staging 
    marts:
      +materialized: table 
